/* ═══════════════════════════════════════════════════════════
   MindTest — база тестов
   Чтобы добавить новый тест — просто допиши объект в массив TESTS.
   Категории и подкатегории описаны в CATEGORIES.
   ═══════════════════════════════════════════════════════════ */

const CATEGORIES = [
  { id: 'all',        name: 'Все тесты',           emoji: '✨' },
  { id: 'psychology', name: 'Психология и характер', emoji: '🧠' },
  { id: 'interests',  name: 'Интересы и хобби',     emoji: '💜' },
  { id: 'talents',    name: 'Таланты и способности', emoji: '✨' },
  { id: 'growth',     name: 'Развитие и цели',      emoji: '🚀' },
  { id: 'knowledge',  name: 'Знания и эрудиция',    emoji: '📚' },
  { id: 'logic',      name: 'Логика и IQ',          emoji: '🧩' }
];

const SUBCATEGORIES = {
  knowledge: [
    { id: 'school',   name: 'Школьные предметы' },
    { id: 'general',  name: 'Общие знания' },
    { id: 'pro',      name: 'Профессиональные' },
    { id: 'creative', name: 'Творческие' }
  ]
};

/* Поля теста:
   id         — уникальный короткий id (латиницей)
   title      — название
   category   — id категории
   subcat     — id подкатегории (только для knowledge)
   desc       — короткое описание
   emoji      — эмодзи-иконка (ты заменишь на картинку)
   time       — время в минутах
   difficulty — 'easy' | 'medium' | 'hard'
   type       — 'result' (без правильных ответов) | 'quiz' (с баллами)
   age        — '12+' | '16+' | '18+'
   badges     — массив бейджей: 'hit', 'new', 'fast', 'hard'
   href       — ссылка на страницу теста (пока '#')
   disclaimer — необязательный текст (для теста на расстройства)
*/

const TESTS = [

  /* ═══════════ ПСИХОЛОГИЯ И ХАРАКТЕР ═══════════ */
  {
    id: 'mbti',
    title: 'Тест на тип личности: 16 типов MBTI — кто ты на самом деле?',
    category: 'psychology',
    desc: 'Узнай свой тип личности по одной из самых известных систем в мире.',
    emoji: '🎭',
    time: 8,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: 'test-mbti.html'
  },
  {
    id: 'hard-character',
    title: 'Тест на тяжёлый характер',
    category: 'psychology',
    desc: 'Проверь, насколько с тобой легко — или сложно — уживаться другим.',
    emoji: '🌪️',
    time: 7,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-hard-character.html'
  },
  {
    id: 'how-others-see',
    title: 'Как тебя видят окружающие: тест на 27 вопросов',
    category: 'psychology',
    desc: 'Ты уверен(а), что знаешь, каким тебя видят другие? Проверим.',
    emoji: '👀',
    time: 7,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast'],
    href: 'test-how-you-seen.html'
  },
  {
    id: 'social-level',
    title: 'Насколько ты социальный человек? Тест на уровень общительности',
    category: 'psychology',
    desc: 'Интроверт, амбиверт или экстраверт? Узнай свой уровень.',
    emoji: '🗣️',
    time: 5,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-social.html'
  },
  {
    id: 'entrepreneur-mind',
    title: 'Есть ли у тебя предпринимательское мышление? Тест для будущих бизнесменов',
    category: 'psychology',
    desc: 'Проверь, готов(а) ли ты мыслить как предприниматель.',
    emoji: '💼',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: 'test-biz.html'
  },
  {
    id: 'optimist-pessimist-realist',
    title: 'Кто ты: оптимист, пессимист или реалист?',
    category: 'psychology',
    desc: 'Узнай, как ты смотришь на мир — через свет, тень или факты.',
    emoji: '☀️',
    time: 4,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: 'test-optimist.html'
  },
  {
    id: 'famous-person',
    title: 'На какую знаменитость ты похож? Тест на характер и типаж',
    category: 'psychology',
    desc: 'Ответь на 27 вопросов — и узнай, какая звезда ближе всего к тебе.',
    emoji: '⭐',
    time: 6,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-famous.html'
  },
  {
    id: 'mental-disorders',
    title: 'Тест на эмоциональное состояние: 8 сфер твоей жизни',
    category: 'psychology',
    desc: 'Настроение, тревога, стресс, сон — 8 сфер твоего состояния.',
    emoji: '🧩',
    time: 10,
    difficulty: 'hard',
    type: 'result',
    age: '14+',
    badges: ['hard'],
    disclaimer: 'Этот тест не является медицинским диагнозом. Если тебе плохо — обратись к психологу или врачу. Ты не один(а).',
    href: 'test-mood.html'
  },
  {
    id: 'emotional-intelligence',
    title: 'Какой у тебя уровень эмоционального интеллекта (EQ)?',
    category: 'psychology',
    desc: 'Умеешь ли ты понимать свои и чужие эмоции? Проверь свой EQ.',
    emoji: '💗',
    time: 8,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-eq.html'
  },
  {
    id: 'place-in-society',
    title: 'Какое твоё место в обществе? Тест на социальную роль',
    category: 'psychology',
    desc: 'Лидер, наблюдатель, душа компании или серый кардинал?',
    emoji: '🏛️',
    time: 6,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-society.html'
  },
  {
    id: 'mutual-feelings',
    title: 'Взаимны ли твои чувства? Тест на любовь и симпатию',
    category: 'psychology',
    desc: 'Ответь честно — и узнай, что происходит между вами.',
    emoji: '💌',
    time: 5,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: ['hit'],
    href: 'test-love.html'
  },
  {
    id: 'addiction',
    title: 'Тест на зависимость: телефон, сигареты, алкоголь, люди',
    category: 'psychology',
    desc: 'Узнай, есть ли у тебя склонность к зависимости — и от чего.',
    emoji: '🔗',
    time: 7,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: 'test-addiction.html'
  },
  {
    id: 'mental-age',
    title: 'Тест: какой у тебя ментальный возраст на самом деле?',
    category: 'psychology',
    desc: 'Сколько лет твоей душе? Возможно, это не то, что ты думаешь.',
    emoji: '🕰️',
    time: 6,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast', 'hit'],
    href: 'test-mental-age.html'
  },
  {
    id: 'ability-to-love',
    title: 'Умеешь ли ты любить? Тест на тип привязанности',
    category: 'psychology',
    desc: 'Понимаешь ли ты, что такое настоящая близость? Проверим.',
    emoji: '❤️',
    time: 7,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: 'test-attachment.html'
  },

  /* ═══════════ ИНТЕРЕСЫ И ХОББИ ═══════════ */
  {
    id: 'hobby-match',
    title: 'Какое хобби тебе подойдёт? Тест на увлечение по душе',
    category: 'interests',
    desc: 'Найдём занятие, от которого ты не сможешь оторваться.',
    emoji: '🎨',
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: 'test-hobby.html'
  },
  {
    id: 'movie-pick',
    title: 'Какое кино тебе стоит посмотреть? Подбор фильма по характеру',
    category: 'interests',
    desc: 'Комедия, драма, триллер или артхаус — что тебе зайдёт прямо сейчас.',
    emoji: '🎬',
    time: 9,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-movie.html'
  },
  {
    id: 'game-match',
    title: 'Какая компьютерная игра тебе подойдёт?',
    category: 'interests',
    desc: 'Шутер, стратегия, RPG или симулятор — найдём игру по тебе.',
    emoji: '🎮',
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-game.html'
  },
  {
    id: 'music-genre',
    title: 'Какой жанр музыки ты полюбишь? Тест на музыкальный вкус',
    category: 'interests',
    desc: 'Рэп, поп, рок, инди, классика — узнай, что тебе ближе.',
    emoji: '🎧',
    time: 7,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-music.html'
  },
  {
    id: 'creative-type',
    title: 'Какой ты творческий тип? Тест на креативность',
    category: 'interests',
    desc: 'Художник, музыкант, писатель или изобретатель? Узнай.',
    emoji: '🎭',
    time: 6,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-creative.html'
  },
  {
    id: 'pet-match',
    title: 'Какая порода кошки или собаки тебе подойдёт?',
    category: 'interests',
    desc: 'Спокойный мейн-кун или энергичный хаски? Найдём питомца по тебе.',
    emoji: '🐾',
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: 'test-pet.html'
  },
  {
    id: 'sport-match',
    title: 'Какой спорт тебе подойдёт? Тест на физический типаж',
    category: 'interests',
    desc: 'Плавание, бег, танцы или единоборства — узнай, что твоё.',
    emoji: '⚽',
    time: 7,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-sport.html'
  },
  {
    id: 'interests-deep',
    title: 'Какие интересы тебе будут по-настоящему близки?',
    category: 'interests',
    desc: 'Узнай, к каким темам тебя тянет — и почему.',
    emoji: '🧭',
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: 'test-interests.html'
  },
  {
    id: 'style-match',
    title: 'Какой стиль одежды тебе подойдёт? Тест на fashion-тип',
    category: 'interests',
    desc: 'Casual, streetwear, классика или спорт-шик? Найдём твой стиль.',
    emoji: '👗',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'makeup-match',
    title: 'Какой макияж тебе подойдёт? Тест на бьюти-типаж',
    category: 'interests',
    desc: 'Натуральный, яркий, готический или гламурный — узнай свой.',
    emoji: '💄',
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },

  /* ═══════════ ТАЛАНТЫ И СПОСОБНОСТИ ═══════════ */
  {
    id: 'sphere-match',
    title: 'Какая сфера тебе подойдёт? Тест на сильную сторону',
    category: 'talents',
    desc: 'Искусство, IT, наука, бьюти или спорт? Найдём твою сферу.',
    emoji: '🧭',
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'thinking-type',
    title: 'Тест на тип мышления: физмат, химбио или гуманитарий?',
    category: 'talents',
    desc: 'Узнай, как работает твой ум — и какие предметы тебе ближе.',
    emoji: '🧠',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'sport-talent',
    title: 'Какой спорт подойдёт именно тебе? Тест на спортивный талант',
    category: 'talents',
    desc: 'Командный, одиночный, силовой или на выносливость? Узнай.',
    emoji: '🏅',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'scientist',
    title: 'Сможешь ли ты стать учёным? Тест на научный склад ума',
    category: 'talents',
    desc: 'Проверь, есть ли у тебя мышление исследователя.',
    emoji: '🔬',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'rich',
    title: 'Сможешь ли ты стать богатым? Тест на финансовое мышление',
    category: 'talents',
    desc: 'Узнай, готов(а) ли ты к большим деньгам — и что тебе мешает.',
    emoji: '💰',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'famous',
    title: 'Сможешь ли ты стать популярным? Тест на харизму',
    category: 'talents',
    desc: 'Есть ли в тебе то, что заставляет людей обращать внимание?',
    emoji: '🌟',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'hidden-talent',
    title: 'Твой скрытый потенциал: тест на талант, о котором ты не знаешь',
    category: 'talents',
    desc: 'Возможно, твой главный талант спрятан глубже, чем кажется.',
    emoji: '💎',
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'beauty-sphere',
    title: 'Сможешь ли ты быть частью бьюти-сферы? Тест для будущих визажистов',
    category: 'talents',
    desc: 'Стиль, вкус, эстетика — всё это можно развить. А у тебя есть задатки?',
    emoji: '💅',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'looksmaxxing',
    title: 'Тест на привлекательность: таблица луксмаксинга',
    category: 'talents',
    desc: 'Оцени свои сильные черты и узнай, как усилить привлекательность.',
    emoji: '🪞',
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'imagination-type',
    title: 'Твой тип воображения: тест на креативное мышление',
    category: 'talents',
    desc: 'Образное, логическое, абстрактное или практическое — какое твоё?',
    emoji: '🎨',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'learning',
    title: 'Насколько хорошо ты усваиваешь новое? Тест на обучаемость',
    category: 'talents',
    desc: 'Визуал, аудиал или кинестетик? Узнай свой стиль обучения.',
    emoji: '📖',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },

  /* ═══════════ РАЗВИТИЕ И ЦЕЛИ ═══════════ */
  {
    id: 'profession-match',
    title: 'Какая профессия тебе подойдёт? Тест на профориентацию',
    category: 'growth',
    desc: 'Ответь на 15 вопросов — и узнай, куда тебе двигаться.',
    emoji: '💼',
    time: 15,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'work-environment',
    title: 'Какая рабочая среда тебе подойдёт? Тест на комфорт в работе',
    category: 'growth',
    desc: 'Офис, удалёнка, фриланс или стартап — где тебе будет хорошо?',
    emoji: '🏢',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'life-goal',
    title: 'Твоя цель на жизнь: тест на главное предназначение',
    category: 'growth',
    desc: 'Узнай, что на самом деле важно для тебя — и как к этому прийти.',
    emoji: '🎯',
    time: 12,
    difficulty: 'hard',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'diet',
    title: 'Какая диета тебе подойдёт? Тест на питание',
    category: 'growth',
    desc: 'Не про моду, а про твой образ жизни и тип обмена веществ.',
    emoji: '🥗',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'university',
    title: 'Куда тебе лучше поступить? Тест на выбор вуза',
    category: 'growth',
    desc: 'Гуманитарный, технический, творческий или медицинский?',
    emoji: '🎓',
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'goal-type',
    title: 'Какой у тебя тип постановки целей? Мечтатель, планировщик или реалист?',
    category: 'growth',
    desc: 'Пойми, как ты ставишь цели — и почему иногда не доходишь до конца.',
    emoji: '📋',
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'motivation-type',
    title: 'Какой у тебя тип мотивации? Тест на внутренний двигатель',
    category: 'growth',
    desc: 'Что заставляет тебя двигаться — страх, интерес, долг или мечта?',
    emoji: '⚡',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'discipline',
    title: 'Твой уровень дисциплины: тест на самоконтроль',
    category: 'growth',
    desc: 'Насколько ты умеешь держать слово, данное самому себе?',
    emoji: '🧘',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'what-distracts',
    title: 'Что сбивает тебя с пути? Тест на внутренние барьеры',
    category: 'growth',
    desc: 'Лень, страх, перфекционизм или чужие ожидания? Узнай.',
    emoji: '🚧',
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'growth-zone',
    title: 'Твоя главная зона роста: тест на личное развитие',
    category: 'growth',
    desc: 'Одна сфера, работа над которой изменит тебя сильнее всего.',
    emoji: '🌱',
    time: 12,
    difficulty: 'hard',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ И ЭРУДИЦИЯ — Школьные ═══════════ */
  {
    id: 'math-5',
    title: 'Математика, 5 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Проверь себя по школьной программе 5 класса.',
    emoji: '➗',
    time: 15,
    difficulty: 'easy',
    type: 'quiz',
    age: '10+',
    badges: [],
    href: '#'
  },
  {
    id: 'math-9',
    title: 'Математика, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Алгебра, геометрия и всё, что было в 9 классе.',
    emoji: '📐',
    time: 20,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'math-11',
    title: 'Математика, 11 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Подготовка к ЕГЭ? Проверь уровень.',
    emoji: '🧮',
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'russian-9',
    title: 'Русский язык, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Орфография, пунктуация, грамматика.',
    emoji: '📝',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'literature-11',
    title: 'Литература, 11 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Серебряный век, советская литература, современность.',
    emoji: '📚',
    time: 20,
    difficulty: 'medium',
    type: 'quiz',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'history-9',
    title: 'История, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'XIX и начало XX века — ключевые события.',
    emoji: '🏛️',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'biology-9',
    title: 'Биология, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Анатомия, генетика, экология.',
    emoji: '🧬',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'chemistry-9',
    title: 'Химия, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Элементы, реакции, задачи.',
    emoji: '⚗️',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'physics-9',
    title: 'Физика, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Механика, электричество, законы Ньютона.',
    emoji: '⚛️',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'geography-9',
    title: 'География, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Страны, регионы, климат.',
    emoji: '🌍',
    time: 15,
    difficulty: 'easy',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'informatics-9',
    title: 'Информатика, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Алгоритмы, системы счисления, основы программирования.',
    emoji: '💻',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'english-9',
    title: 'Английский язык, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Grammar, vocabulary, reading.',
    emoji: '🇬🇧',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'social-9',
    title: 'Обществознание, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Право, экономика, социум.',
    emoji: '⚖️',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ — Общие ═══════════ */
  {
    id: 'safety',
    title: 'Тест на знание безопасности: проверь, готов(а) ли ты к разным ситуациям',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Пожар, первая помощь, интернет-безопасность.',
    emoji: '🛡️',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'english-level',
    title: 'Тест на уровень английского языка: A1–C1',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Узнай свой реальный уровень за 15 минут.',
    emoji: '🔤',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'medicine',
    title: 'Тест на знание медицины: базовые вопросы',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Первая помощь, лекарства, организм человека.',
    emoji: '🩺',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'astronomy',
    title: 'Тест на знание астрономии: планеты, звёзды, космос',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Проверь, насколько хорошо ты знаешь Вселенную.',
    emoji: '🪐',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'history-culture',
    title: 'Тест на знание истории и культуры',
    category: 'knowledge',
    subcat: 'general',
    desc: 'От древнего мира до современности.',
    emoji: '🏺',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'vocabulary',
    title: 'Тест на словарный запас: насколько богат твой язык?',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Узнай, сколько редких слов ты знаешь.',
    emoji: '📖',
    time: 10,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: ['fast'],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ — Профессиональные ═══════════ */
  {
    id: 'programming',
    title: 'Тест на знание программирования: основы для всех',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Переменные, циклы, функции, алгоритмы.',
    emoji: '👨‍💻',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'ai',
    title: 'Тест на знание ИИ: понимаешь ли ты, как работают нейросети?',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'ChatGPT, машинное обучение, промпты.',
    emoji: '🤖',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: ['new'],
    href: '#'
  },
  {
    id: 'laws-rf',
    title: 'Тест на знание законов РФ: базовые права и обязанности',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Конституция, права ребёнка, базовая юридика.',
    emoji: '⚖️',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'finances',
    title: 'Тест на финансовую грамотность: умеешь ли ты обращаться с деньгами?',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Бюджет, сбережения, инвестиции простыми словами.',
    emoji: '💳',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'university-1',
    title: 'Тест вузовского уровня №1: гуманитарные науки',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Для тех, кто хочет проверить себя выше школьной программы.',
    emoji: '🎓',
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-2',
    title: 'Тест вузовского уровня №2: естественные науки',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Биология, химия, физика — университетский уровень.',
    emoji: '🎓',
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-3',
    title: 'Тест вузовского уровня №3: экономика и право',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Проверь себя на взрослом уровне.',
    emoji: '🎓',
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-4',
    title: 'Тест вузовского уровня №4: IT и математика',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Дискретка, алгоритмы, матан — для смелых.',
    emoji: '🎓',
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-5',
    title: 'Тест вузовского уровня №5: искусство и культура',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Живопись, архитектура, музыка, кино.',
    emoji: '🎓',
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ — Творческие ═══════════ */
  {
    id: 'guitar',
    title: 'Тест на знание игры на гитаре',
    category: 'knowledge',
    subcat: 'creative',
    desc: 'Аккорды, табы, техника.',
    emoji: '🎸',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'piano',
    title: 'Тест на знание игры на фортепиано',
    category: 'knowledge',
    subcat: 'creative',
    desc: 'Ноты, гаммы, произведения.',
    emoji: '🎹',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'drums',
    title: 'Тест на знание игры на барабанах',
    category: 'knowledge',
    subcat: 'creative',
    desc: 'Ритм, размеры, техника.',
    emoji: '🥁',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ЛОГИКА И IQ ═══════════ */
  {
    id: 'iq',
    title: 'Тест на IQ: узнай свой уровень интеллекта',
    category: 'logic',
    desc: '20 заданий на логику, внимание и мышление.',
    emoji: '🧠',
    time: 20,
    difficulty: 'hard',
    type: 'quiz',
    age: '14+',
    badges: ['hit', 'hard'],
    href: '#'
  },
  {
    id: 'mind-type',
    title: 'Тест на склад ума: аналитик, творец или стратег?',
    category: 'logic',
    desc: 'Как устроено твоё мышление и где ты сильнее всего.',
    emoji: '🎯',
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'logical-thinking',
    title: 'Тест на логическое мышление: 15 задач',
    category: 'logic',
    desc: 'Проверь, насколько быстро ты находишь закономерности.',
    emoji: '🧩',
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'memory',
    title: 'Тест на память: как хорошо ты запоминаешь?',
    category: 'logic',
    desc: 'Проверь кратковременную и долговременную память.',
    emoji: '💭',
    time: 10,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },
  {
    id: 'attention',
    title: 'Тест на внимание и концентрацию',
    category: 'logic',
    desc: 'Насколько легко тебя отвлечь?',
    emoji: '🔍',
    time: 10,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'speed-thinking',
    title: 'Тест на скорость мышления: успеешь ли ты за временем?',
    category: 'logic',
    desc: 'Простые задачи, но против секундомера.',
    emoji: '⚡',
    time: 8,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },
  {
    id: 'creativity-logic',
    title: 'Тест на креативное мышление: сможешь ли ты придумать нестандартное решение?',
    category: 'logic',
    desc: 'Логика + воображение = креативность.',
    emoji: '💡',
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'lateral',
    title: 'Тест на латеральное мышление: задачи с подвохом',
    category: 'logic',
    desc: 'Иногда очевидный ответ — неправильный.',
    emoji: '🎭',
    time: 12,
    difficulty: 'hard',
    type: 'quiz',
    age: '14+',
    badges: ['hard'],
    href: '#'
  }
];
