/* ═══════════════════════════════════════════════════════════
   MindTest — база тестов
   Чтобы добавить новый тест — просто допиши объект в массив TESTS.
   Категории и подкатегории описаны в CATEGORIES.
   Иконки — SVG в стиле MindTest (фиолетовая обводка).
   ═══════════════════════════════════════════════════════════ */

const ICONS = {
  all:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>',
  psychology: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/></svg>',
  interests:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
  talents:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>',
  growth:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2 3 14h9l-1 8 10-12h-9l1-8z"/></svg>',
  knowledge:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>',
  logic:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 11H3v10h6V11z"/><path d="M21 3h-6v10h6V3z"/><path d="M9 7H3v2h6V7z"/><path d="M21 15h-6v2h6v-2z"/></svg>',

  // ── Иконки для карточек тестов ──
  mask:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12c0-3 1.5-5 4-5 2 0 3 1 6 1s4-1 6-1c2.5 0 4 2 4 5s-1.5 5-4 5c-2 0-3-1-6-1s-4 1-6 1c-2.5 0-4-2-4-5z"/><circle cx="8" cy="11" r="1"/><circle cx="16" cy="11" r="1"/></svg>',
  tornado:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 4h18"/><path d="M5 8h14"/><path d="M7 12h10"/><path d="M9 16h6"/><path d="M11 20h2"/></svg>',
  eye:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg>',
  chat:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>',
  briefcase:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>',
  sun:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>',
  star:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>',
  puzzle:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 3a2 2 0 1 1 4 0v1h4a1 1 0 0 1 1 1v4h1a2 2 0 1 1 0 4h-1v4a1 1 0 0 1-1 1h-4v1a2 2 0 1 1-4 0v-1H6a1 1 0 0 1-1-1v-4H4a2 2 0 1 1 0-4h1V5a1 1 0 0 1 1-1h4z"/></svg>',
  heart:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
  envelope:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 6-10 7L2 6"/></svg>',
  link:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>',
  clock:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>',
  palette:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="13.5" cy="6.5" r=".5"/><circle cx="17.5" cy="10.5" r=".5"/><circle cx="8.5" cy="7.5" r=".5"/><circle cx="6.5" cy="12.5" r=".5"/><path d="M12 2a10 10 0 0 0 0 20c1.1 0 2-.9 2-2 0-.5-.2-1-.5-1.3-.3-.4-.5-.8-.5-1.4 0-1.1.9-2 2-2H17a5 5 0 0 0 5-5c0-4.5-4.5-8.3-10-8.3z"/></svg>',
  film:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="18" rx="2"/><path d="M7 3v18M17 3v18M2 8h5M2 12h5M2 16h5M17 8h5M17 12h5M17 16h5"/></svg>',
  book:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>',
  gamepad:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="10" rx="4"/><path d="M7 12h2M8 11v2M15 11h.01M18 13h.01"/></svg>',
  headphones: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14v-2a8 8 0 0 1 16 0v2"/><rect x="2" y="14" width="4" height="6" rx="1"/><rect x="18" y="14" width="4" height="6" rx="1"/></svg>',
  paw:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="5" cy="10" r="2"/><circle cx="9" cy="5" r="2"/><circle cx="15" cy="5" r="2"/><circle cx="19" cy="10" r="2"/><path d="M12 21c-3 0-5-2-5-4 0-1.5 1-2.5 2.5-3S12 14 12 14s1 0 2.5.5S17 15.5 17 17c0 2-2 4-5 4z"/></svg>',
  ball:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="m12 2 3 5-3 5-3-5z"/><path d="m2 12 5 3 5-3 5 3 5-3"/></svg>',
  compass:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></svg>',
  dress:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 2h6l-2 5h3l-4 15h-4L4 7h3z"/></svg>',
  lipstick:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="2" width="8" height="8" rx="1"/><rect x="7" y="10" width="10" height="12" rx="1.5"/></svg>',
  medal:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="15" r="6"/><path d="m8 2 2 6M16 2l-2 6"/><path d="m12 12 1 2 2 .5-1.5 1.5.5 2-2-1-2 1 .5-2L9 14.5l2-.5z"/></svg>',
  flask:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 3h6v6l4 10a2 2 0 0 1-2 3H7a2 2 0 0 1-2-3l4-10z"/><path d="M7 14h10"/></svg>',
  money:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="6" width="20" height="12" rx="2"/><circle cx="12" cy="12" r="3"/></svg>',
  diamond:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 3h12l4 6-10 12L2 9z"/><path d="M2 9h20M12 3 8 9l4 12M12 3l4 6-4 12"/></svg>',
  mirror:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="9" r="7"/><path d="M12 16v6"/><path d="M9 19h6"/></svg>',
  target:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>',
  building:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="1"/><path d="M9 6h1M14 6h1M9 10h1M14 10h1M9 14h1M14 14h1M10 22v-4h4v4"/></svg>',
  salad:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 11h18a9 9 0 0 1-18 0z"/><path d="M7 7a3 3 0 0 1 3-3 3 3 0 0 1 3 3"/><path d="M13 7a3 3 0 0 1 3-3 3 3 0 0 1 3 3"/></svg>',
  cap:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 9 12 4l10 5-10 5z"/><path d="M6 11v5c0 1 3 3 6 3s6-2 6-3v-5"/></svg>',
  clipboard:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="2" width="8" height="4" rx="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><path d="M9 12h6M9 16h4"/></svg>',
  bolt:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2 3 14h9l-1 8 10-12h-9l1-8z"/></svg>',
  lotus:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 4c2 3 2 6 0 9-2-3-2-6 0-9z"/><path d="M5 10c3 0 5 2 7 5-3 0-6-1-7-5z"/><path d="M19 10c-3 0-5 2-7 5 3 0 6-1 7-5z"/><path d="M3 17c3-1 6-1 9 1 3-2 6-2 9-1"/></svg>',
  barrier:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8h16v3H4zM4 16h16v3H4z"/><path d="M8 8V4M12 8V4M16 8V4"/></svg>',
  sprout:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22V8"/><path d="M12 8C12 4 9 2 5 2c0 4 3 6 7 6z"/><path d="M12 12c0-3 2-5 6-5 0 3-3 5-6 5z"/></svg>',
  divide:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="6" r="2"/><circle cx="12" cy="18" r="2"/><path d="M4 12h16"/></svg>',
  ruler:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="10" rx="1" transform="rotate(-15 12 12)"/><path d="M7 9v2M11 8v2M15 7v2M19 6v2"/></svg>',
  calculator: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><rect x="7" y="5" width="10" height="4" rx="1"/><path d="M8 13h.01M12 13h.01M16 13h.01M8 17h.01M12 17h.01M16 17h.01"/></svg>',
  pen:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 1 1 3 3L7 19l-4 1 1-4z"/></svg>',
  library:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 4h5v16H2zM9 4h5v16H9zM16 5l5 1-3 15-5-1z"/></svg>',
  landmark:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M4 21V10h4v11M10 21V10h4v11M16 21V10h4v11M2 10 12 3l10 7"/></svg>',
  dna:        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4c4 4 12 4 16 0M4 20c4-4 12-4 16 0M8 4v16M16 4v16"/></svg>',
  atom:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="2"/><ellipse cx="12" cy="12" rx="10" ry="4"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)"/></svg>',
  globe:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2c3 3 3 17 0 20M12 2c-3 3-3 17 0 20"/></svg>',
  laptop:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M2 20h20"/></svg>',
  flag:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V4M4 4h12l-2 4 2 4H4"/></svg>',
  scales:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18M5 7h14M5 7 2 14a3 3 0 0 0 6 0L5 7zM19 7l-3 7a3 3 0 0 0 6 0l-3-7z"/></svg>',
  shield:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>',
  ab:         '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 18 7 6l4 12M4.5 14h5M14 6h4a3 3 0 0 1 0 6h-4zM14 12h4a3 3 0 0 1 0 6h-4z"/></svg>',
  stethoscope:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 3v6a5 5 0 0 0 10 0V3"/><path d="M11 14v2a4 4 0 0 0 8 0v-2"/><circle cx="19" cy="12" r="2"/></svg>',
  saturn:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="6"/><path d="M3 12c0-2 4-4 9-4s9 2 9 4-4 4-9 4-9-2-9-4z"/></svg>',
  amphora:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 3h6M10 3v3c0 2-3 3-3 7s2 6 5 8c3-2 5-4 5-8s-3-5-3-7V3"/></svg>',
  vocab:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h12a4 4 0 0 1 4 4v12H8a4 4 0 0 1-4-4z"/><path d="M8 8h8M8 12h8"/></svg>',
  code:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
  robot:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="8" width="16" height="12" rx="2"/><path d="M12 4v4M8 14h.01M16 14h.01M9 18h6"/></svg>',
  gavel:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m14 13-7 7-3-3 7-7"/><path d="m13 14 6-6-3-3-6 6"/><path d="m16 5 3 3"/></svg>',
  card:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/></svg>',
  graduation: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 10 12 5 2 10l10 5 10-5z"/><path d="M6 12v5c0 1 3 3 6 3s6-2 6-3v-5"/><path d="M22 10v6"/></svg>',
  guitar:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 3a2 2 0 0 1 1.4 3.4L17 10a4 4 0 0 1-3 7 5 5 0 0 1-5 4 4 4 0 0 1-3-7 5 5 0 0 1 4-5 4 4 0 0 1 7-3z"/><circle cx="14" cy="14" r="2"/></svg>',
  piano:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="6" width="20" height="12" rx="2"/><path d="M7 6v8M11 6v8M15 6v8M19 6v8"/></svg>',
  drums:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="8" rx="9" ry="3"/><path d="M3 8v10c0 1.7 4 3 9 3s9-1.3 9-3V8"/></svg>',
  brain:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/></svg>',
  maze:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h6v6h-6z"/><path d="M9 6h6M6 9v6M18 9v6M9 18h6"/></svg>',
  bulb:       '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18h6M10 22h4M12 2a7 7 0 0 0-4 12.7V17h8v-2.3A7 7 0 0 0 12 2z"/></svg>',
  domino:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M4 12h16"/><circle cx="9" cy="7" r="1"/><circle cx="15" cy="7" r="1"/><circle cx="9" cy="17" r="1"/><circle cx="15" cy="17" r="1"/></svg>',
  memory:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M9 9h.01M15 9h.01M9 15h.01M15 15h.01M12 12h.01"/></svg>',
  search:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"/><path d="m21 21-4.3-4.3"/></svg>',
  hourglass:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2h12M6 22h12M8 2v4l4 4 4-4V2M8 22v-4l4-4 4 4v4"/></svg>'
};

const CATEGORIES = [
  { id: 'all',        name: 'Все тесты',              icon: ICONS.all },
  { id: 'psychology', name: 'Психология и характер',  icon: ICONS.psychology },
  { id: 'interests',  name: 'Интересы и хобби',       icon: ICONS.interests },
  { id: 'talents',    name: 'Таланты и способности',  icon: ICONS.talents },
  { id: 'growth',     name: 'Развитие и цели',        icon: ICONS.growth },
  { id: 'knowledge',  name: 'Знания и эрудиция',      icon: ICONS.knowledge },
  { id: 'logic',      name: 'Логика и IQ',            icon: ICONS.logic }
];

const SUBCATEGORIES = {
  knowledge: [
    { id: 'school',   name: 'Школьные предметы' },
    { id: 'general',  name: 'Общие знания' },
    { id: 'pro',      name: 'Профессиональные' },
    { id: 'creative', name: 'Творческие' }
  ]
};

/* Поля теста:
   id         — уникальный короткий id (латиницей)
   title      — название
   category   — id категории
   subcat     — id подкатегории (только для knowledge)
   desc       — короткое описание
   icon       — SVG-иконка (ключ из ICONS)
   time       — время в минутах
   difficulty — 'easy' | 'medium' | 'hard'
   type       — 'result' (без правильных ответов) | 'quiz' (с баллами)
   age        — '12+' | '16+' | '18+'
   badges     — массив бейджей: 'hit', 'new', 'fast', 'hard'
   href       — ссылка на страницу теста (пока '#')
   disclaimer — необязательный текст (для теста на расстройства)
*/

const TESTS = [

  /* ═══════════ ПСИХОЛОГИЯ И ХАРАКТЕР ═══════════ */
  {
    id: 'mbti',
    title: 'Тест на тип личности: 16 типов MBTI — кто ты на самом деле?',
    category: 'psychology',
    desc: 'Узнай свой тип личности по одной из самых известных систем в мире.',
    icon: ICONS.mask,
    time: 15,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'hard-character',
    title: 'Тест на тяжёлый характер',
    category: 'psychology',
    desc: 'Проверь, насколько с тобой легко — или сложно — уживаться другим.',
    icon: ICONS.tornado,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'how-others-see',
    title: 'Как тебя видят окружающие: тест на 10 вопросов',
    category: 'psychology',
    desc: 'Ты уверен(а), что знаешь, каким тебя видят другие? Проверим.',
    icon: ICONS.eye,
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },
  {
    id: 'social-level',
    title: 'Насколько ты социальный человек? Тест на уровень общительности',
    category: 'psychology',
    desc: 'Интроверт, амбиверт или экстраверт? Узнай свой уровень.',
    icon: ICONS.chat,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'entrepreneur-mind',
    title: 'Есть ли у тебя предпринимательское мышление? Тест для будущих бизнесменов',
    category: 'psychology',
    desc: 'Проверь, готов(а) ли ты мыслить как предприниматель.',
    icon: ICONS.briefcase,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'optimist-pessimist-realist',
    title: 'Кто ты: оптимист, пессимист или реалист?',
    category: 'psychology',
    desc: 'Узнай, как ты смотришь на мир — через свет, тень или факты.',
    icon: ICONS.sun,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: 'test-optimist.html'
  },
  {
    id: 'famous-person',
    title: 'На какую знаменитость ты похож? Тест на характер и типаж',
    category: 'psychology',
    desc: 'Ответь на 12 вопросов — и узнай, какая звезда ближе всего к тебе.',
    icon: ICONS.star,
    time: 12,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'mental-disorders',
    title: 'Тест на склонность к психологическим расстройствам',
    category: 'psychology',
    desc: 'Проверь уровень тревожности и склонность к депрессивным состояниям.',
    icon: ICONS.puzzle,
    time: 15,
    difficulty: 'hard',
    type: 'result',
    age: '16+',
    badges: ['hard'],
    disclaimer: 'Этот тест не является медицинским диагнозом. Если тебе плохо — обратись к психологу или врачу. Ты не один(а).',
    href: '#'
  },
  {
    id: 'emotional-intelligence',
    title: 'Какой у тебя уровень эмоционального интеллекта (EQ)?',
    category: 'psychology',
    desc: 'Умеешь ли ты понимать свои и чужие эмоции? Проверь свой EQ.',
    icon: ICONS.heart,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'place-in-society',
    title: 'Какое твоё место в обществе? Тест на социальную роль',
    category: 'psychology',
    desc: 'Лидер, наблюдатель, душа компании или серый кардинал?',
    icon: ICONS.landmark,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'mutual-feelings',
    title: 'Взаимны ли твои чувства? Тест на любовь и симпатию',
    category: 'psychology',
    desc: 'Ответь честно — и узнай, что происходит между вами.',
    icon: ICONS.envelope,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'addiction',
    title: 'Тест на зависимость: телефон, сигареты, алкоголь, люди',
    category: 'psychology',
    desc: 'Узнай, есть ли у тебя склонность к зависимости — и от чего.',
    icon: ICONS.link,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'mental-age',
    title: 'Тест: какой у тебя ментальный возраст на самом деле?',
    category: 'psychology',
    desc: 'Сколько лет твоей душе? Возможно, это не то, что ты думаешь.',
    icon: ICONS.clock,
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast', 'hit'],
    href: '#'
  },
  {
    id: 'ability-to-love',
    title: 'Умеешь ли ты любить? Тест на тип привязанности',
    category: 'psychology',
    desc: 'Понимаешь ли ты, что такое настоящая близость? Проверим.',
    icon: ICONS.heart,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ИНТЕРЕСЫ И ХОББИ ═══════════ */
  {
    id: 'hobby-match',
    title: 'Какое хобби тебе подойдёт? Тест на увлечение по душе',
    category: 'interests',
    desc: 'Найдём занятие, от которого ты не сможешь оторваться.',
    icon: ICONS.palette,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'movie-pick',
    title: 'Какое кино тебе стоит посмотреть? Подбор фильма по характеру',
    category: 'interests',
    desc: 'Комедия, драма, триллер или артхаус — что тебе зайдёт прямо сейчас.',
    icon: ICONS.film,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'anime-naruto',
    title: 'Кто ты из Наруто? Тест на персонажа',
    category: 'interests',
    desc: 'Наруто, Саске, Сакура или Какаши? Узнай, кто ты из Конохи.',
    icon: ICONS.book,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'anime-deathnote',
    title: 'Кто ты из Тетради смерти? Тест на персонажа',
    category: 'interests',
    desc: 'Лайт, L, Миса или Ниа? Узнай, чья стратегия ближе тебе.',
    icon: ICONS.book,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'series-mean-girls',
    title: 'Кто ты из «Дрянных девчонок»? Тест на персонажа',
    category: 'interests',
    desc: 'Реджина, Кэди, Дженис или Гретчен? Узнай свою роль.',
    icon: ICONS.film,
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },
  {
    id: 'game-match',
    title: 'Какая компьютерная игра тебе подойдёт?',
    category: 'interests',
    desc: 'Шутер, стратегия, RPG или симулятор — найдём игру по тебе.',
    icon: ICONS.gamepad,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'music-genre',
    title: 'Какой жанр музыки ты полюбишь? Тест на музыкальный вкус',
    category: 'interests',
    desc: 'Рэп, поп, рок, инди, классика — узнай, что тебе ближе.',
    icon: ICONS.headphones,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'creative-type',
    title: 'Какой ты творческий тип? Тест на креативность',
    category: 'interests',
    desc: 'Художник, музыкант, писатель или изобретатель? Узнай.',
    icon: ICONS.palette,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'pet-match',
    title: 'Какая порода кошки или собаки тебе подойдёт?',
    category: 'interests',
    desc: 'Спокойный мейн-кун или энергичный хаски? Найдём питомца по тебе.',
    icon: ICONS.paw,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'sport-match',
    title: 'Какой спорт тебе подойдёт? Тест на физический типаж',
    category: 'interests',
    desc: 'Плавание, бег, танцы или единоборства — узнай, что твоё.',
    icon: ICONS.ball,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'interests-deep',
    title: 'Какие интересы тебе будут по-настоящему близки?',
    category: 'interests',
    desc: 'Узнай, к каким темам тебя тянет — и почему.',
    icon: ICONS.compass,
    time: 12,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'style-match',
    title: 'Какой стиль одежды тебе подойдёт? Тест на fashion-тип',
    category: 'interests',
    desc: 'Casual, streetwear, классика или спорт-шик? Найдём твой стиль.',
    icon: ICONS.dress,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'makeup-match',
    title: 'Какой макияж тебе подойдёт? Тест на бьюти-типаж',
    category: 'interests',
    desc: 'Натуральный, яркий, готический или гламурный — узнай свой.',
    icon: ICONS.lipstick,
    time: 8,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },

  /* ═══════════ ТАЛАНТЫ И СПОСОБНОСТИ ═══════════ */
  {
    id: 'sphere-match',
    title: 'Какая сфера тебе подойдёт? Тест на сильную сторону',
    category: 'talents',
    desc: 'Искусство, IT, наука, бьюти или спорт? Найдём твою сферу.',
    icon: ICONS.compass,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'thinking-type',
    title: 'Тест на тип мышления: физмат, химбио или гуманитарий?',
    category: 'talents',
    desc: 'Узнай, как работает твой ум — и какие предметы тебе ближе.',
    icon: ICONS.brain,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'sport-talent',
    title: 'Какой спорт подойдёт именно тебе? Тест на спортивный талант',
    category: 'talents',
    desc: 'Командный, одиночный, силовой или на выносливость? Узнай.',
    icon: ICONS.medal,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'scientist',
    title: 'Сможешь ли ты стать учёным? Тест на научный склад ума',
    category: 'talents',
    desc: 'Проверь, есть ли у тебя мышление исследователя.',
    icon: ICONS.flask,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'rich',
    title: 'Сможешь ли ты стать богатым? Тест на финансовое мышление',
    category: 'talents',
    desc: 'Узнай, готов(а) ли ты к большим деньгам — и что тебе мешает.',
    icon: ICONS.money,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'famous',
    title: 'Сможешь ли ты стать популярным? Тест на харизму',
    category: 'talents',
    desc: 'Есть ли в тебе то, что заставляет людей обращать внимание?',
    icon: ICONS.star,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'hidden-talent',
    title: 'Твой скрытый потенциал: тест на талант, о котором ты не знаешь',
    category: 'talents',
    desc: 'Возможно, твой главный талант спрятан глубже, чем кажется.',
    icon: ICONS.diamond,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'beauty-sphere',
    title: 'Сможешь ли ты быть частью бьюти-сферы? Тест для будущих визажистов',
    category: 'talents',
    desc: 'Стиль, вкус, эстетика — всё это можно развить. А у тебя есть задатки?',
    icon: ICONS.lipstick,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'looksmaxxing',
    title: 'Тест на привлекательность: таблица луксмаксинга',
    category: 'talents',
    desc: 'Оцени свои сильные черты и узнай, как усилить привлекательность.',
    icon: ICONS.mirror,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'imagination-type',
    title: 'Твой тип воображения: тест на креативное мышление',
    category: 'talents',
    desc: 'Образное, логическое, абстрактное или практическое — какое твоё?',
    icon: ICONS.palette,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'learning',
    title: 'Насколько хорошо ты усваиваешь новое? Тест на обучаемость',
    category: 'talents',
    desc: 'Визуал, аудиал или кинестетик? Узнай свой стиль обучения.',
    icon: ICONS.book,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '12+',
    badges: [],
    href: '#'
  },

  /* ═══════════ РАЗВИТИЕ И ЦЕЛИ ═══════════ */
  {
    id: 'profession-match',
    title: 'Какая профессия тебе подойдёт? Тест на профориентацию',
    category: 'growth',
    desc: 'Ответь на 15 вопросов — и узнай, куда тебе двигаться.',
    icon: ICONS.briefcase,
    time: 15,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'work-environment',
    title: 'Какая рабочая среда тебе подойдёт? Тест на комфорт в работе',
    category: 'growth',
    desc: 'Офис, удалёнка, фриланс или стартап — где тебе будет хорошо?',
    icon: ICONS.building,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'life-goal',
    title: 'Твоя цель на жизнь: тест на главное предназначение',
    category: 'growth',
    desc: 'Узнай, что на самом деле важно для тебя — и как к этому прийти.',
    icon: ICONS.target,
    time: 12,
    difficulty: 'hard',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'diet',
    title: 'Какая диета тебе подойдёт? Тест на питание',
    category: 'growth',
    desc: 'Не про моду, а про твой образ жизни и тип обмена веществ.',
    icon: ICONS.salad,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'university',
    title: 'Куда тебе лучше поступить? Тест на выбор вуза',
    category: 'growth',
    desc: 'Гуманитарный, технический, творческий или медицинский?',
    icon: ICONS.graduation,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'goal-type',
    title: 'Какой у тебя тип постановки целей? Мечтатель, планировщик или реалист?',
    category: 'growth',
    desc: 'Пойми, как ты ставишь цели — и почему иногда не доходишь до конца.',
    icon: ICONS.clipboard,
    time: 10,
    difficulty: 'easy',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'motivation-type',
    title: 'Какой у тебя тип мотивации? Тест на внутренний двигатель',
    category: 'growth',
    desc: 'Что заставляет тебя двигаться — страх, интерес, долг или мечта?',
    icon: ICONS.bolt,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'discipline',
    title: 'Твой уровень дисциплины: тест на самоконтроль',
    category: 'growth',
    desc: 'Насколько ты умеешь держать слово, данное самому себе?',
    icon: ICONS.lotus,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'what-distracts',
    title: 'Что сбивает тебя с пути? Тест на внутренние барьеры',
    category: 'growth',
    desc: 'Лень, страх, перфекционизм или чужие ожидания? Узнай.',
    icon: ICONS.barrier,
    time: 10,
    difficulty: 'medium',
    type: 'result',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'growth-zone',
    title: 'Твоя главная зона роста: тест на личное развитие',
    category: 'growth',
    desc: 'Одна сфера, работа над которой изменит тебя сильнее всего.',
    icon: ICONS.sprout,
    time: 12,
    difficulty: 'hard',
    type: 'result',
    age: '16+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ И ЭРУДИЦИЯ — Школьные ═══════════ */
  {
    id: 'math-5',
    title: 'Математика, 5 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Проверь себя по школьной программе 5 класса.',
    icon: ICONS.divide,
    time: 15,
    difficulty: 'easy',
    type: 'quiz',
    age: '10+',
    badges: [],
    href: '#'
  },
  {
    id: 'math-9',
    title: 'Математика, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Алгебра, геометрия и всё, что было в 9 классе.',
    icon: ICONS.ruler,
    time: 20,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'math-11',
    title: 'Математика, 11 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Подготовка к ЕГЭ? Проверь уровень.',
    icon: ICONS.calculator,
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'russian-9',
    title: 'Русский язык, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Орфография, пунктуация, грамматика.',
    icon: ICONS.pen,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'literature-11',
    title: 'Литература, 11 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Серебряный век, советская литература, современность.',
    icon: ICONS.library,
    time: 20,
    difficulty: 'medium',
    type: 'quiz',
    age: '16+',
    badges: [],
    href: '#'
  },
  {
    id: 'history-9',
    title: 'История, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'XIX и начало XX века — ключевые события.',
    icon: ICONS.landmark,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'biology-9',
    title: 'Биология, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Анатомия, генетика, экология.',
    icon: ICONS.dna,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'chemistry-9',
    title: 'Химия, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Элементы, реакции, задачи.',
    icon: ICONS.flask,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'physics-9',
    title: 'Физика, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Механика, электричество, законы Ньютона.',
    icon: ICONS.atom,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'geography-9',
    title: 'География, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Страны, регионы, климат.',
    icon: ICONS.globe,
    time: 15,
    difficulty: 'easy',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'informatics-9',
    title: 'Информатика, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Алгоритмы, системы счисления, основы программирования.',
    icon: ICONS.laptop,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'english-9',
    title: 'Английский язык, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Grammar, vocabulary, reading.',
    icon: ICONS.flag,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'social-9',
    title: 'Обществознание, 9 класс: тест на знания',
    category: 'knowledge',
    subcat: 'school',
    desc: 'Право, экономика, социум.',
    icon: ICONS.scales,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ — Общие ═══════════ */
  {
    id: 'safety',
    title: 'Тест на знание безопасности: проверь, готов(а) ли ты к разным ситуациям',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Пожар, первая помощь, интернет-безопасность.',
    icon: ICONS.shield,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'english-level',
    title: 'Тест на уровень английского языка: A1–C1',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Узнай свой реальный уровень за 15 минут.',
    icon: ICONS.ab,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'medicine',
    title: 'Тест на знание медицины: базовые вопросы',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Первая помощь, лекарства, организм человека.',
    icon: ICONS.stethoscope,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'astronomy',
    title: 'Тест на знание астрономии: планеты, звёзды, космос',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Проверь, насколько хорошо ты знаешь Вселенную.',
    icon: ICONS.saturn,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'history-culture',
    title: 'Тест на знание истории и культуры',
    category: 'knowledge',
    subcat: 'general',
    desc: 'От древнего мира до современности.',
    icon: ICONS.amphora,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'vocabulary',
    title: 'Тест на словарный запас: насколько богат твой язык?',
    category: 'knowledge',
    subcat: 'general',
    desc: 'Узнай, сколько редких слов ты знаешь.',
    icon: ICONS.vocab,
    time: 10,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: ['fast'],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ — Профессиональные ═══════════ */
  {
    id: 'programming',
    title: 'Тест на знание программирования: основы для всех',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Переменные, циклы, функции, алгоритмы.',
    icon: ICONS.code,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'ai',
    title: 'Тест на знание ИИ: понимаешь ли ты, как работают нейросети?',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'ChatGPT, машинное обучение, промпты.',
    icon: ICONS.robot,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: ['new'],
    href: '#'
  },
  {
    id: 'laws-rf',
    title: 'Тест на знание законов РФ: базовые права и обязанности',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Конституция, права ребёнка, базовая юридика.',
    icon: ICONS.gavel,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: [],
    href: '#'
  },
  {
    id: 'finances',
    title: 'Тест на финансовую грамотность: умеешь ли ты обращаться с деньгами?',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Бюджет, сбережения, инвестиции простыми словами.',
    icon: ICONS.card,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '14+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'university-1',
    title: 'Тест вузовского уровня №1: гуманитарные науки',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Для тех, кто хочет проверить себя выше школьной программы.',
    icon: ICONS.graduation,
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-2',
    title: 'Тест вузовского уровня №2: естественные науки',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Биология, химия, физика — университетский уровень.',
    icon: ICONS.graduation,
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-3',
    title: 'Тест вузовского уровня №3: экономика и право',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Проверь себя на взрослом уровне.',
    icon: ICONS.graduation,
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-4',
    title: 'Тест вузовского уровня №4: IT и математика',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Дискретка, алгоритмы, матан — для смелых.',
    icon: ICONS.graduation,
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },
  {
    id: 'university-5',
    title: 'Тест вузовского уровня №5: искусство и культура',
    category: 'knowledge',
    subcat: 'pro',
    desc: 'Живопись, архитектура, музыка, кино.',
    icon: ICONS.graduation,
    time: 25,
    difficulty: 'hard',
    type: 'quiz',
    age: '16+',
    badges: ['hard'],
    href: '#'
  },

  /* ═══════════ ЗНАНИЯ — Творческие ═══════════ */
  {
    id: 'guitar',
    title: 'Тест на знание игры на гитаре',
    category: 'knowledge',
    subcat: 'creative',
    desc: 'Аккорды, табы, техника.',
    icon: ICONS.guitar,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'piano',
    title: 'Тест на знание игры на фортепиано',
    category: 'knowledge',
    subcat: 'creative',
    desc: 'Ноты, гаммы, произведения.',
    icon: ICONS.piano,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'drums',
    title: 'Тест на знание игры на барабанах',
    category: 'knowledge',
    subcat: 'creative',
    desc: 'Ритм, размеры, техника.',
    icon: ICONS.drums,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },

  /* ═══════════ ЛОГИКА И IQ ═══════════ */
  {
    id: 'iq',
    title: 'Тест на IQ: узнай свой уровень интеллекта',
    category: 'logic',
    desc: '20 заданий на логику, внимание и мышление.',
    icon: ICONS.brain,
    time: 20,
    difficulty: 'hard',
    type: 'quiz',
    age: '14+',
    badges: ['hit', 'hard'],
    href: '#'
  },
  {
    id: 'mind-type',
    title: 'Тест на склад ума: аналитик, творец или стратег?',
    category: 'logic',
    desc: 'Как устроено твоё мышление и где ты сильнее всего.',
    icon: ICONS.target,
    time: 12,
    difficulty: 'medium',
    type: 'result',
    age: '12+',
    badges: ['hit'],
    href: '#'
  },
  {
    id: 'logical-thinking',
    title: 'Тест на логическое мышление: 15 задач',
    category: 'logic',
    desc: 'Проверь, насколько быстро ты находишь закономерности.',
    icon: ICONS.maze,
    time: 15,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'memory',
    title: 'Тест на память: как хорошо ты запоминаешь?',
    category: 'logic',
    desc: 'Проверь кратковременную и долговременную память.',
    icon: ICONS.memory,
    time: 10,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },
  {
    id: 'attention',
    title: 'Тест на внимание и концентрацию',
    category: 'logic',
    desc: 'Насколько легко тебя отвлечь?',
    icon: ICONS.search,
    time: 10,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'speed-thinking',
    title: 'Тест на скорость мышления: успеешь ли ты за временем?',
    category: 'logic',
    desc: 'Простые задачи, но против секундомера.',
    icon: ICONS.hourglass,
    time: 8,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: ['fast'],
    href: '#'
  },
  {
    id: 'creativity-logic',
    title: 'Тест на креативное мышление: сможешь ли ты придумать нестандартное решение?',
    category: 'logic',
    desc: 'Логика + воображение = креативность.',
    icon: ICONS.bulb,
    time: 12,
    difficulty: 'medium',
    type: 'quiz',
    age: '12+',
    badges: [],
    href: '#'
  },
  {
    id: 'lateral',
    title: 'Тест на латеральное мышление: задачи с подвохом',
    category: 'logic',
    desc: 'Иногда очевидный ответ — неправильный.',
    icon: ICONS.domino,
    time: 12,
    difficulty: 'hard',
    type: 'quiz',
    age: '14+',
    badges: ['hard'],
    href: '#'
  }
];
